package com.example;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class Transaction extends org.drools.persistence.jpa.marshaller.VariableEntity {

	static final long serialVersionUID = 1L;

	private java.lang.String account;
	private java.lang.Double amount;
	private java.lang.String source;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "TRANSACTION_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "TRANSACTION_ID_SEQ", name = "TRANSACTION_ID_GENERATOR")
	private java.lang.Long id;

	public Transaction() {
	}

	public java.lang.String getAccount() {
		return this.account;
	}

	public void setAccount(java.lang.String account) {
		this.account = account;
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.String getSource() {
		return this.source;
	}

	public void setSource(java.lang.String source) {
		this.source = source;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Transaction(java.lang.String account, java.lang.Double amount,
			java.lang.String source, java.lang.Long id) {
		this.account = account;
		this.amount = amount;
		this.source = source;
		this.id = id;
	}

}